### PR TITLE
Add a hack to backslash

### PR DESCRIPTION
**Pull request by hatoo**
#17
It seems that backslash is duplicated during `let doc = iter.next().unwrap().to_string()`.
I added a dirty hack to address this but a more fundamental solution is appreciated.

@magurotuna do you have any thoughts on the issue?

### CODE REVIEW

**Comment by magurotuna** [comment]
Hmm... to be honest I have no idea about that for now :-(
Could you give me some time to look into this? I'm wondering how proc_macro2 handles backslashes in doc comments.

**Comment by magurotuna** [comment]
Sorry for taking long time.

As you pointed out, duplicated backslash seems a `proc_macro2` problem, almost similar to #15.
In `proc_marco2`, it uses `escape_debug` to process characters in token stream.
The backslash character, which is represented like `'\\'` in Rust, is passed to `escape_debug` and then it is turned into an iterator that has two items: `'\\'` `'\\'`. So duplication happens.

Though your hack works fine, we would be happier if the essential problem in `proc_macro2` could be solved. I've created a new PR to it:
[Avoid unnecessary escapes for string and character literal by magurotuna · Pull Request #217 · alexcrichton/proc-macro2](https://github.com/alexcrichton/proc-macro2/pull/217)


By the way, during my browsing, I found a very useful feature in rustfmt:
[normalize_doc_attributes · rust-lang/rustfmt](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#normalize_doc_attributes)
Unfortunately only in nightly it can be used for now, but it deserves to be checked and tracked.

**Comment by magurotuna** [comment]
My PR for proc_macro2 was closed. My understanding was wrong.

I read through proc_macro2, syn, quote, and rustc code today.  My conclusion is that our backslash problem is caused by the processing of doc comments,  which re-sugar doc comments.
Our parser re-sugars doc comments like `#[doc = "foobar"]` into `/// foobar`, and this process requires to deal with the content of it (= `foobar`). 
`foobar` in `#[doc = "foobar"]`  is _NOT raw string literal_, but in `/// foobar` it's _JUST raw string literal_. We have to fill the gap between them.

So your current workaround looks a good way to do this. But I think more fix would be necessary for other escaped characters such as `\t`, `\"`.
May I do the additional implementation? Or would you like to implement it for yourself?

**Comment by hatoo** [comment]
> May I do the additional implementation? Or would you like to implement it for yourself?

I'm very happy if you implement this because you are more familiar than me with this issue.
But feel free to let me know me if you are busy.

**Comment by magurotuna** [comment]
Sure, I'll implement it 💪
But as weekdays are coming, give me one week at the longest.

**Pull request merged**
